### ISSUE TITLE
schema.d.ts for astrocite-bibtex misses parameter in signature for parse

### ISSUE THREAD

**Issue by retorquere** [dsifford/astrocite#23]
The signature for 

```
export declare function parse(input: string, options?: ParseOptions): AST;
```

changed to 

```
export function parse(input: string): CSL.Data[];
```

but the parser still supports `options`. I also get an error

```
TS2503: Cannot find namespace 'CSL'.
```

when I try to use the new signature.

**Comment by retorquere** [comment]
Oh wait, I see now.

I was previously just importing `astrocite-bibtex/lib/grammar`, and the typings would work with that. I can of course import 

```
const bibtexAST = AST.parse(`
@article{my_article,
    title = {Hello world},
    journal = "Some Journal"
}
`);
```

as shown in the readme (sorry about that), but that pull in all of astrocite-bibtex rather than just the grammar (I use webpack, so the lot gets bundled in). Any ideas on how I can import just the grammar?

**Comment by dsifford** [comment]
If you use just the types off of `AST`, and don't actually call a function, webpack should skip right over and not add it to your bundle (depending on how you're bundling with webpack).

**Comment by retorquere** [comment]
Yeah my bad -- I had previously just copied `schema.d.ts` to `grammar.d.ts` and that isn't right anymore. https://github.com/dsifford/astrocite/pull/24 fixes this.
