### ISSUE TITLE
@comments in the AST

### ISSUE THREAD

**Issue by retorquere** [dsifford/astrocite#6]
Currently, `@comments` like

```
@comment stuff

@comment{ more stuff }
```

don't show up in the AST. Would it be possible to add these?

**Comment by dsifford** [comment]
Yes, those can be added. I'm not sure why I decided to just skip over those. Probably because I just assumed they didn't serve any value. But if you think there is some value to that, it shouldn't be too terribly difficult to add in.

**Comment by dsifford** [comment]
See here: https://github.com/dsifford/astrocite/blob/7b3c081282c30652cf91fe70996b3fe4174f8d80/packages/astrocite-bibtex/src/grammar.pegjs#L38-L40

**Comment by retorquere** [comment]
Do you want  me to issue a PR for these?

**Comment by retorquere** [comment]
PR for this is in #9
